#!/usr/bin/env python3
"""
Full Stack Developer Skill for Hermes Lite
Provides professional developer workflow: plan → implement → test → deploy
Based on 2024 web development best practices
"""

import json
import os
import subprocess
from pathlib import Path
from typing import Dict, List, Optional, Any

class FullStackDevSkill:
    """Professional full stack development workflow skill"""
    
    def __init__(self):
        self.name = "full_stack_dev"
        self.description = "Professional full stack development workflow: plan, implement, test, deploy"
        self.version = "1.0.0"
        self.author = "Hermes Lite"
    
    def execute(self, agent, project_description: str, tech_stack: str = "auto", 
                output_dir: str = "./project") -> str:
        """
        Execute full stack development workflow
        
        Args:
            agent: The Hermes Lite agent instance
            project_description: Description of what to build
            tech_stack: Preferred tech stack (auto, react-node, vue-python, etc.)
            output_dir: Directory to create the project in
            
        Returns:
            Result of the development workflow
        """
        try:
            # Phase 1: Planning
            print("🔍 Phase 1: Planning the project...")
            plan_result = self._create_project_plan(agent, project_description, tech_stack)
            
            # Phase 2: Implementation
            print("🔨 Phase 2: Implementing the project...")
            impl_result = self._implement_project(agent, plan_result, output_dir)
            
            # Phase 3: Testing
            print("🧪 Phase 3: Testing the implementation...")
            test_result = self._test_project(agent, output_dir)
            
            # Phase 4: Deployment preparation
            print("🚀 Phase 4: Preparing for deployment...")
            deploy_result = self._prepare_deployment(agent, output_dir)
            
            return f"""✅ Full stack development workflow completed!

📋 PLAN: {plan_result}
🔧 IMPLEMENTATION: {impl_result}
🧪 TESTING: {test_result}
🚀 DEPLOYMENT PREP: {deploy_result}

Project created in: {output_dir}
Next steps: Review the generated code, run tests, and deploy as needed."""
            
        except Exception as e:
            return f"❌ Error in full stack development workflow: {str(e)}"
    
    def _create_project_plan(self, agent, description: str, tech_stack: str) -> str:
        """Create a detailed project plan using the agent"""
        planning_prompt = f"""You are a senior full stack architect. Create a concise but complete plan for this project:

PROJECT: {description}
TECH STACK PREFERENCE: {tech_stack}

Provide:
1. Core features (3-5 max)
2. Tech stack recommendation (frontend/backend/database)
3. File structure outline
4. Key APIs/endpoints needed
5. Estimated complexity (simple/medium/complex)

Be concise - this is for token efficiency. Use bullet points."""
        
        try:
            plan = agent.chat(planning_prompt)
            return plan[:200] + "..." if len(plan) > 200 else plan
        except Exception as e:
            return f"Planning fallback: {description} - Basic web app with REST API"
    
    def _implement_project(self, agent, plan: str, output_dir: str) -> str:
        """Implement the project based on the plan"""
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)
        
        # Create basic file structure
        files_created = []
        
        # README
        readme_content = f"""# {plan.split(chr(10))[0] if plan else 'Full Stack Project'}

## Overview
Generated by Hermes Lite Full Stack Developer Skill

## Features
- Modern full stack application
- Responsive design
- RESTful API
- Basic testing setup

## Tech Stack
- Frontend: React/Vue/HTML-CSS-JS
- Backend: Node.js/Python/FastAPI
- Database: SQLite/PostgreSQL/MongoDB

## Setup
1. Install dependencies
2. Configure environment
3. Run development server
4. Run tests

## Generated by
Hermes Lite - Your AI development partner
"""
        
        (output_path / "README.md").write_text(readme_content)
        files_created.append("README.md")
        
        # Basic frontend structure
        frontend_dir = output_path / "frontend"
        frontend_dir.mkdir(exist_ok=True)
        
        (frontend_dir / "index.html").write_text("""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Full Stack App</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 0; padding: 20px; }
        .container { max-width: 800px; margin: 0 auto; }
        header { background: #007bff; color: white; padding: 20px; text-align: center; }
        .content { margin: 20px 0; }
        footer { text-align: center; padding: 20px; color: #666; }
    </style>
</head>
<body>
    <header>
        <h1>Full Stack Application</h1>
    </header>
    <div class="container">
        <div class="content">
            <h2>Welcome to your app!</h2>
            <p>This is a generated full stack application.</p>
            <button onclick="fetchData()">Load Data</button>
            <div id="data"></div>
        </div>
    </div>
    <footer>
        <p>Generated by Hermes Lite</p>
    </footer>
    <script>
        async function fetchData() {
            try {
                const response = await fetch('/api/data');
                const data = await response.json();
                document.getElementById('data').innerHTML = '<pre>' + JSON.stringify(data, null, 2) + '</pre>';
            } catch (error) {
                document.getElementById('data').innerHTML = '<p>Error loading data</p>';
            }
        }
    </script>
</body>
</html>""")
        files_created.append("frontend/index.html")
        
        # Basic backend structure (Python/FastAPI)
        backend_dir = output_path / "backend"
        backend_dir.mkdir(exist_ok=True)
        
        (backend_dir / "main.py").write_text("""from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import uvicorn
from typing import List, Dict, Any

app = FastAPI(title="Full Stack API", version="1.0.0")

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
async def root():
    return {"message": "Hello World from Full Stack API"}

@app.get("/api/data")
async def get_data():
    return {
        "items": [
            {"id": 1, "name": "Item 1", "description": "Sample item"},
            {"id": 2, "name": "Item 2", "description": "Another sample item"}
        ],
        "timestamp": "2024-01-01T00:00:00Z"
    }

@app.post("/api/items")
async def create_item(item: Dict[str, Any]):
    return {"message": "Item created", "item": item}

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
""")
        files_created.append("backend/main.py")
        
        (backend_dir / "requirements.txt").write_text("""fastapi>=0.68.0
uvicorn>=0.15.0
pydantic>=1.8.0
""")
        files_created.append("backend/requirements.txt")
        
        # Basic test structure
        tests_dir = output_path / "tests"
        tests_dir.mkdir(exist_ok=True)
        
        (tests_dir / "test_api.py").write_text("""import unittest
import sys
import os

# Add backend to path
sys.path.append(os.path.join(os.path.dirname(__file__), 'backend'))

class TestAPI(unittest.TestCase):
    def test_root_endpoint(self):
        # This would be implemented with actual test client
        self.assertTrue(True, "Placeholder test")
    
    def test_data_endpoint(self):
        # This would be implemented with actual test client
        self.assertTrue(True, "Placeholder test")

if __name__ == '__main__':
    unittest.main()
""")
        files_created.append("tests/test_api.py")
        
        # Dockerfile for easy deployment
        (output_path / "Dockerfile").write_text("""FROM python:3.9-slim

WORKDIR /app

# Copy backend requirements
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY backend/ ./backend/
COPY frontend/ ./frontend/

# Expose port
EXPOSE 8000

# Start the application
CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
""")
        files_created.append("Dockerfile")
        
        return f"Created {len(files_created)} files: {', '.join(files_created[:5])}{'...' if len(files_created) > 5 else ''}"
    
    def _test_project(self, agent, output_dir: str) -> str:
        """Run basic tests on the project"""
        output_path = Path(output_dir)
        test_results = []
        
        # Check if files exist
        required_files = [
            "README.md",
            "frontend/index.html",
            "backend/main.py",
            "backend/requirements.txt",
            "tests/test_api.py",
            "Dockerfile"
        ]
        
        missing_files = []
        for file_req in required_files:
            if not (output_path / file_req).exists():
                missing_files.append(file_req)
        
        if missing_files:
            test_results.append(f"❌ Missing files: {', '.join(missing_files)}")
        else:
            test_results.append("✅ All required files present")
        
        # Check Python syntax
        try:
            result = subprocess.run([
                "python3", "-m", "py_compile", 
                str(output_path / "backend" / "main.py")
            ], capture_output=True, text=True, timeout=10)
            
            if result.returncode == 0:
                test_results.append("✅ Backend Python syntax valid")
            else:
                test_results.append(f"❌ Backend Python syntax error: {result.stderr[:100]}")
        except Exception as e:
            test_results.append(f"⚠️ Could not check Python syntax: {str(e)[:50]}")
        
        # Check if we can install dependencies (dry run)
        try:
            req_file = output_path / "backend" / "requirements.txt"
            if req_file.exists():
                test_results.append("✅ Requirements file found")
            else:
                test_results.append("❌ Requirements file missing")
        except Exception as e:
            test_results.append(f"⚠️ Requirements check failed: {str(e)[:50]}")
        
        return "; ".join(test_results)
    
    def _prepare_deployment(self, agent, output_dir: str) -> str:
        """Prepare deployment instructions and configurations"""
        output_path = Path(output_dir)
        
        # Create deployment instructions
        deploy_info = []
        
        # Docker deployment
        deploy_info.append("🐡 Docker: docker build -t fullstack-app . && docker run -p 8000:8000 fullstack-app")
        
        # Heroku-like deployment
        (output_path / "Procfile").write_text("web: uvicorn backend.main:app --host=0.0.0.0 --port=$PORT")
        deploy_info.append("📱 Platform-as-a-Service: Procfile created")
        
        # Vercel/Netlify frontend notice
        deploy_info.append("🌐 Frontend: Static HTML/CSS/JS - deploy to Vercel, Netlify, or any static host")
        
        # Environment variables example
        (output_path / ".env.example").write_text("""# Environment variables
PORT=8000
DEBUG=False
# Add your API keys here
DATABASE_URL=sqlite:///./app.db
""")
        deploy_info.append("⚙️ Environment: .env.example created")
        
        return "; ".join(deploy_info)

# Register the skill when module is imported
skill = FullStackDevSkill()